cmake .. \
  -DCMAKE_C_COMPILER=clang \
  -DCMAKE_CXX_COMPILER=clang++ \
  -DCMAKE_Fortran_COMPILER=mpifort \
  -DCMAKE_C_FLAGS="-Wno-error -march=znver2" \
  -DCMAKE_CXX_FLAGS="-stdlib=libc++ -Wno-error -Dgsl_FEATURE_GSL_COMPATIBILITY_MODE=1 -Dgsl_CONFIG_DEFAULTS_VERSION=1 -march=znver2" \
  -DCMAKE_Fortran_FLAGS="-Wno-error -march=znver2 -ffree-form -DSINGLE_PRECISION" \
  -DCMAKE_Fortran_FLAGS_RELEASE="-O3 -g -march=znver2 -ffree-form -DSINGLE_PRECISION" \
  -DNetCDF_CXX_LIBRARY=/usr/lib/libnetcdf-cxx4.so \
  -DNetCDF_CXX_INCLUDE_DIR=/usr/include \
  -DOOPS_ENABLE_STACKTRACE=OFF \
  -DOOPS_STACKTRACE_PROVIDER=none \
  -DBUILD_TESTING=OFF \
  -DENABLE_TESTS=OFF \
  -DCMAKE_BUILD_TYPE=Release
